// Auto-generated by @bymav/vita-domain — DO NOT EDIT
// Source: data/*.json | Regenerate: node generate.mjs

import Foundation

// MARK: - VitaDomain

enum VitaDomain {

    // MARK: Gamification

    static let levelThresholds: [Int] = [0, 100, 250, 500, 1000, 2000, 3500, 5500, 8000, 11000, 15000, 20000, 26000, 33000, 41000, 50000, 60000, 72000, 85000, 100000, 120000, 142000, 168000, 198000, 232000, 270000, 315000, 365000, 420000, 500000]

    static let xpRewards: [String: Int] = [
        "flashcard_review": 10,
        "flashcard_easy": 15,
        "question_answered": 10,
        "chat_message": 5,
        "note_created": 20,
        "note_edited": 5,
        "document_annotated": 15,
        "daily_login": 25,
        "deck_completed": 50,
        "simulado_complete": 30,
        "osce_completed": 40,
        "qbank_session_complete": 25,
        "studio_generated": 15,
        "study_session_end": 10,
        "document_opened": 5,
        "simulado_start": 5,
        "study_session_start": 0,
    ]

    static let badgeXp: [String: Int] = [
        "first_review": 25,
        "cards_50": 50,
        "cards_100": 75,
        "cards_500": 150,
        "cards_1000": 300,
        "cards_2500": 500,
        "streak_3": 30,
        "streak_7": 75,
        "streak_14": 150,
        "streak_30": 300,
        "streak_60": 500,
        "streak_100": 1000,
        "level_3": 50,
        "level_5": 100,
        "level_10": 200,
        "level_15": 400,
        "level_20": 750,
        "first_note": 25,
        "notes_10": 75,
        "notes_50": 200,
        "night_owl": 30,
        "early_bird": 30,
        "weekend_warrior": 50,
        "first_chat": 25,
        "chat_50": 100,
    ]

    struct Badge {
        let id: String
        let name: String
        let description: String
        let icon: String
        let category: String
    }

    static let allBadges: [Badge] = [
        Badge(id: "first_review", name: "Primeira Revisao", description: "Complete sua primeira sessao de flashcards", icon: "school", category: "cards"),
        Badge(id: "cards_50", name: "Aprendiz", description: "Revise 50 flashcards", icon: "style", category: "cards"),
        Badge(id: "cards_100", name: "Centuriao", description: "Revise 100 flashcards", icon: "style", category: "cards"),
        Badge(id: "cards_500", name: "Mestre dos Cards", description: "500 flashcards revisados", icon: "auto_awesome", category: "cards"),
        Badge(id: "cards_1000", name: "Lenda", description: "1000 flashcards", icon: "emoji_events", category: "cards"),
        Badge(id: "cards_2500", name: "Enciclopedia", description: "2500 flashcards revisados", icon: "menu_book", category: "cards"),
        Badge(id: "streak_3", name: "3 Dias Seguidos", description: "Mantenha uma sequencia de 3 dias", icon: "local_fire_department", category: "streak"),
        Badge(id: "streak_7", name: "Semana Perfeita", description: "7 dias seguidos estudando", icon: "whatshot", category: "streak"),
        Badge(id: "streak_14", name: "Quinzenista", description: "14 dias seguidos estudando", icon: "whatshot", category: "streak"),
        Badge(id: "streak_30", name: "Mes Dedicado", description: "30 dias seguidos", icon: "military_tech", category: "streak"),
        Badge(id: "streak_60", name: "Veterano", description: "60 dias seguidos estudando", icon: "military_tech", category: "streak"),
        Badge(id: "streak_100", name: "Lendario", description: "100 dias seguidos estudando", icon: "emoji_events", category: "streak"),
        Badge(id: "level_3", name: "Calouro", description: "Alcance nivel 3", icon: "trending_up", category: "milestone"),
        Badge(id: "level_5", name: "Estudante Dedicado", description: "Alcance nivel 5", icon: "trending_up", category: "milestone"),
        Badge(id: "level_10", name: "Residente", description: "Alcance nivel 10", icon: "workspace_premium", category: "milestone"),
        Badge(id: "level_15", name: "Especialista", description: "Alcance nivel 15", icon: "workspace_premium", category: "milestone"),
        Badge(id: "level_20", name: "Mestre", description: "Alcance nivel 20", icon: "emoji_events", category: "milestone"),
        Badge(id: "first_note", name: "Anotador", description: "Crie sua primeira nota", icon: "edit_note", category: "study"),
        Badge(id: "notes_10", name: "Escriba", description: "Crie 10 notas", icon: "edit_note", category: "study"),
        Badge(id: "notes_50", name: "Cronista", description: "Crie 50 notas", icon: "edit_note", category: "study"),
        Badge(id: "night_owl", name: "Coruja", description: "Estude depois das 22h", icon: "dark_mode", category: "study"),
        Badge(id: "early_bird", name: "Madrugador", description: "Estude antes das 7h", icon: "wb_sunny", category: "study"),
        Badge(id: "weekend_warrior", name: "Guerreiro de Fim de Semana", description: "Estude no sabado e domingo", icon: "sports_esports", category: "study"),
        Badge(id: "first_chat", name: "Curioso", description: "Faca sua primeira pergunta a Vita", icon: "chat", category: "social"),
        Badge(id: "chat_50", name: "Filosofo", description: "Faca 50 perguntas a Vita", icon: "chat", category: "social"),
    ]

    static let streakBonusThreshold = 7
    static let streakBonusXp = 10
    static let dailyGoal = 50

    // MARK: Subjects & Curriculum

    struct Cycle {
        let id: String
        let name: String
        let years: [Int]
        let description: String
    }

    static let cycles: [Cycle] = [
        Cycle(id: "basico", name: "Ciclo Basico", years: [1, 2], description: "Ciencias biomedicas fundamentais"),
        Cycle(id: "clinico", name: "Ciclo Clinico", years: [3, 4], description: "Aplicacao clinica e diagnostico"),
        Cycle(id: "internato", name: "Internato", years: [5, 6], description: "Pratica hospitalar supervisionada"),
    ]

    struct Subject {
        let id: String
        let name: String
        let icon: String
        let color: String
        let year: [Int]
        let cycle: String
        let description: String
    }

    static let subjects: [Subject] = [
        Subject(id: "anatomia", name: "Anatomia Humana", icon: "Bone", color: "bg-red-500", year: [1], cycle: "basico", description: "Anatomia sistematica e topografica"),
        Subject(id: "histologia", name: "Histologia e Embriologia", icon: "Microscope", color: "bg-pink-500", year: [1], cycle: "basico", description: "Tecidos e desenvolvimento embrionario"),
        Subject(id: "bioquimica", name: "Bioquimica", icon: "FlaskConical", color: "bg-purple-500", year: [1], cycle: "basico", description: "Metabolismo e reacoes quimicas"),
        Subject(id: "biofisica", name: "Biofisica", icon: "Atom", color: "bg-violet-500", year: [1], cycle: "basico", description: "Principios fisicos aplicados"),
        Subject(id: "biologia-celular", name: "Biologia Celular e Molecular", icon: "Dna", color: "bg-fuchsia-500", year: [1], cycle: "basico", description: "Genetica basica, DNA, RNA"),
        Subject(id: "fisiologia-1", name: "Fisiologia Humana I", icon: "HeartPulse", color: "bg-rose-500", year: [1], cycle: "basico", description: "Sistemas cardiovascular, respiratorio, renal"),
        Subject(id: "saude-coletiva-1", name: "Saude Coletiva I", icon: "Users", color: "bg-teal-500", year: [1], cycle: "basico", description: "SUS e epidemiologia basica"),
        Subject(id: "etica-medica", name: "Etica Medica", icon: "Scale", color: "bg-amber-500", year: [1], cycle: "basico", description: "Bioetica e deontologia"),
        Subject(id: "psicologia-medica", name: "Psicologia Medica", icon: "Brain", color: "bg-amber-500", year: [1], cycle: "basico", description: "Relacao medico-paciente"),
        Subject(id: "fisiologia-2", name: "Fisiologia Humana II", icon: "Activity", color: "bg-rose-600", year: [2], cycle: "basico", description: "Sistemas nervoso, endocrino, digestivo"),
        Subject(id: "patologia-geral", name: "Patologia Geral", icon: "SearchX", color: "bg-orange-500", year: [2], cycle: "basico", description: "Processos patologicos basicos"),
        Subject(id: "farmacologia", name: "Farmacologia Basica", icon: "Pill", color: "bg-blue-500", year: [2], cycle: "basico", description: "Farmacocinetica e farmacodinamica"),
        Subject(id: "microbiologia", name: "Microbiologia", icon: "Bug", color: "bg-lime-500", year: [2], cycle: "basico", description: "Bacteriologia, virologia, micologia"),
        Subject(id: "parasitologia", name: "Parasitologia", icon: "Worm", color: "bg-green-500", year: [2], cycle: "basico", description: "Protozoarios e helmintos"),
        Subject(id: "imunologia", name: "Imunologia", icon: "Shield", color: "bg-sky-500", year: [2], cycle: "basico", description: "Sistema imune e anticorpos"),
        Subject(id: "genetica", name: "Genetica Medica", icon: "Dna", color: "bg-indigo-500", year: [2], cycle: "basico", description: "Heranca e doencas geneticas"),
        Subject(id: "epidemiologia", name: "Epidemiologia / Bioestatistica", icon: "BarChart3", color: "bg-emerald-500", year: [2], cycle: "basico", description: "Desenho de estudos e estatistica"),
        Subject(id: "semiologia", name: "Semiologia", icon: "Stethoscope", color: "bg-indigo-600", year: [3], cycle: "clinico", description: "Anamnese e exame fisico"),
        Subject(id: "patologia-especial", name: "Patologia Especial", icon: "FileSearch", color: "bg-orange-600", year: [3], cycle: "clinico", description: "Patologia por orgao e sistema"),
        Subject(id: "farmacologia-clinica", name: "Farmacologia Clinica", icon: "Syringe", color: "bg-blue-600", year: [3], cycle: "clinico", description: "Prescricao racional"),
        Subject(id: "clinica-medica-1", name: "Clinica Medica I", icon: "ClipboardList", color: "bg-indigo-500", year: [3], cycle: "clinico", description: "Grandes sindromes clinicas"),
        Subject(id: "cirurgia-1", name: "Cirurgia I", icon: "Scissors", color: "bg-red-600", year: [3], cycle: "clinico", description: "Tecnica operatoria e principios"),
        Subject(id: "pediatria-1", name: "Pediatria I", icon: "Baby", color: "bg-pink-400", year: [3], cycle: "clinico", description: "Puericultura e desenvolvimento"),
        Subject(id: "go-1", name: "Ginecologia e Obstetricia I", icon: "Heart", color: "bg-rose-400", year: [3], cycle: "clinico", description: "Ciclo menstrual e pre-natal"),
        Subject(id: "psiquiatria-1", name: "Psiquiatria I", icon: "BrainCircuit", color: "bg-purple-400", year: [3], cycle: "clinico", description: "Transtornos psiquiatricos"),
        Subject(id: "mfc-1", name: "Medicina de Familia I", icon: "Home", color: "bg-teal-400", year: [3], cycle: "clinico", description: "Pratica na UBS"),
        Subject(id: "radiologia", name: "Radiologia", icon: "ScanLine", color: "bg-gray-500", year: [3], cycle: "clinico", description: "Raio-X, TC, RM"),
        Subject(id: "clinica-medica-2", name: "Clinica Medica II", icon: "ClipboardPlus", color: "bg-indigo-700", year: [4], cycle: "clinico", description: "Cardio, endocrino, nefro, hemato, infecto"),
        Subject(id: "cirurgia-2", name: "Cirurgia II", icon: "Swords", color: "bg-red-700", year: [4], cycle: "clinico", description: "Trauma e urgencias abdominais"),
        Subject(id: "pediatria-2", name: "Pediatria II", icon: "Baby", color: "bg-pink-600", year: [4], cycle: "clinico", description: "Neonatologia e emergencias"),
        Subject(id: "go-2", name: "Ginecologia e Obstetricia II", icon: "Heart", color: "bg-rose-600", year: [4], cycle: "clinico", description: "Parto e patologias obstetricas"),
        Subject(id: "ortopedia", name: "Ortopedia", icon: "Bone", color: "bg-amber-600", year: [4], cycle: "clinico", description: "Fraturas e traumatologia"),
        Subject(id: "oftalmologia", name: "Oftalmologia", icon: "Eye", color: "bg-amber-600", year: [4], cycle: "clinico", description: "Doencas oculares"),
        Subject(id: "otorrino", name: "Otorrinolaringologia", icon: "Ear", color: "bg-yellow-600", year: [4], cycle: "clinico", description: "Ouvido, nariz, garganta"),
        Subject(id: "dermatologia", name: "Dermatologia", icon: "Fingerprint", color: "bg-orange-400", year: [4], cycle: "clinico", description: "Doencas cutaneas"),
        Subject(id: "neurologia", name: "Neurologia", icon: "BrainCog", color: "bg-violet-600", year: [4], cycle: "clinico", description: "Sistema nervoso"),
        Subject(id: "internato-cm", name: "Clinica Medica (Rodizio)", icon: "Building2", color: "bg-indigo-500", year: [5, 6], cycle: "internato", description: "Enfermaria e pronto-socorro"),
        Subject(id: "internato-cir", name: "Cirurgia Geral (Rodizio)", icon: "Hospital", color: "bg-red-500", year: [5, 6], cycle: "internato", description: "Centro cirurgico e urgencia"),
        Subject(id: "internato-ped", name: "Pediatria (Rodizio)", icon: "Baby", color: "bg-pink-500", year: [5, 6], cycle: "internato", description: "Enfermaria e PA infantil"),
        Subject(id: "internato-go", name: "GO (Rodizio)", icon: "Heart", color: "bg-rose-500", year: [5, 6], cycle: "internato", description: "Pre-natal e sala de parto"),
        Subject(id: "internato-sc", name: "Saude Coletiva (Rodizio)", icon: "Users", color: "bg-teal-500", year: [5, 6], cycle: "internato", description: "UBS e PSF"),
        Subject(id: "internato-ue", name: "Urgencia e Emergencia", icon: "Siren", color: "bg-red-600", year: [5, 6], cycle: "internato", description: "Pronto-socorro geral"),
    ]

    struct ExamBoard {
        let id: String
        let name: String
        let description: String
        let format: String
    }

    static let examBoards: [ExamBoard] = [
        ExamBoard(id: "usp-sp", name: "USP-SP (FMUSP)", description: "Conceitual, casos longos", format: "120 questoes multipla escolha"),
        ExamBoard(id: "unicamp", name: "UNICAMP", description: "Discursiva, raciocinio puro", format: "100 questoes discursivas"),
        ExamBoard(id: "enare", name: "ENARE", description: "Nacional, maior volume", format: "100 questoes multipla escolha"),
        ExamBoard(id: "sus-sp", name: "SUS-SP", description: "Protocolar, foco SUS", format: "Multipla escolha"),
        ExamBoard(id: "santa-casa", name: "Santa Casa SP", description: "Classica, equilibrada", format: "100 questoes multipla escolha"),
        ExamBoard(id: "usp-rp", name: "USP-RP", description: "Equilibrada teoria/pratica", format: "Objetiva + OSCE"),
    ]

    struct ResidencyArea {
        let id: String
        let name: String
        let duration: String
        let access: String
    }

    static let residencyAreas: [ResidencyArea] = [
        ResidencyArea(id: "clinica-medica", name: "Clinica Medica", duration: "2 anos", access: "direto"),
        ResidencyArea(id: "cirurgia-geral", name: "Cirurgia Geral", duration: "3 anos", access: "direto"),
        ResidencyArea(id: "pediatria", name: "Pediatria", duration: "3 anos", access: "direto"),
        ResidencyArea(id: "go", name: "Ginecologia e Obstetricia", duration: "3 anos", access: "direto"),
        ResidencyArea(id: "ortopedia", name: "Ortopedia e Traumatologia", duration: "3 anos", access: "direto"),
        ResidencyArea(id: "dermatologia", name: "Dermatologia", duration: "3 anos", access: "direto"),
        ResidencyArea(id: "oftalmologia", name: "Oftalmologia", duration: "3 anos", access: "direto"),
        ResidencyArea(id: "psiquiatria", name: "Psiquiatria", duration: "3 anos", access: "direto"),
        ResidencyArea(id: "neurologia", name: "Neurologia", duration: "3 anos", access: "direto"),
        ResidencyArea(id: "anestesiologia", name: "Anestesiologia", duration: "3 anos", access: "direto"),
        ResidencyArea(id: "radiologia", name: "Radiologia", duration: "3 anos", access: "direto"),
        ResidencyArea(id: "mfc", name: "Medicina de Familia e Comunidade", duration: "2 anos", access: "direto"),
        ResidencyArea(id: "emergencia", name: "Medicina de Emergencia", duration: "3 anos", access: "direto"),
        ResidencyArea(id: "otorrino", name: "Otorrinolaringologia", duration: "3 anos", access: "direto"),
        ResidencyArea(id: "infectologia", name: "Infectologia", duration: "3 anos", access: "direto"),
        ResidencyArea(id: "cardiologia", name: "Cardiologia", duration: "2 anos", access: "pre-requisito: Clinica Medica"),
        ResidencyArea(id: "gastro", name: "Gastroenterologia", duration: "2 anos", access: "pre-requisito: Clinica Medica"),
        ResidencyArea(id: "nefrologia", name: "Nefrologia", duration: "2 anos", access: "pre-requisito: Clinica Medica"),
        ResidencyArea(id: "cirurgia-plastica", name: "Cirurgia Plastica", duration: "3 anos", access: "pre-requisito: Cirurgia Geral"),
        ResidencyArea(id: "neurocirurgia", name: "Neurocirurgia", duration: "5 anos", access: "direto"),
    ]

    // MARK: Study Methods

    struct StudyMethod {
        let id: String
        let name: String
        let icon: String
        let description: String
        let howItWorks: String
        let optimalDuration: String
    }

    static let studyMethods: [StudyMethod] = [
        StudyMethod(id: "pomodoro", name: "Pomodoro", icon: "Timer", description: "Sessoes focadas de 25min com pausas de 5min", howItWorks: "4 ciclos de 25min estudo + 5min pausa. Apos 4 ciclos, pausa longa de 15-30min.", optimalDuration: "2h por bloco (4 pomodoros)"),
        StudyMethod(id: "active-recall", name: "Active Recall", icon: "Brain", description: "Testar-se ativamente em vez de reler", howItWorks: "Apos estudar um topico, feche o material e tente lembrar tudo. O esforco de recuperacao fortalece a memoria.", optimalDuration: "10-15min por topico"),
        StudyMethod(id: "spaced-repetition", name: "Repeticao Espacada", icon: "CalendarClock", description: "Revisar em intervalos crescentes (1d, 3d, 7d, 14d...)", howItWorks: "Algoritmo FSRS ajusta intervalos com base no seu desempenho. Cards faceis aparecem menos, dificeis aparecem mais.", optimalDuration: "20-30min por dia de revisao"),
        StudyMethod(id: "feynman", name: "Tecnica Feynman", icon: "MessageCircle", description: "Explique o conceito como se fosse para uma crianca", howItWorks: "Se voce nao consegue explicar de forma simples, nao entendeu de verdade. Identifica gaps no conhecimento.", optimalDuration: "15-20min por conceito"),
        StudyMethod(id: "interleaving", name: "Intercalacao", icon: "Shuffle", description: "Misturar materias em vez de estudar uma so por vez", howItWorks: "Alternar entre topicos diferentes numa sessao. Melhora discriminacao e transferencia de conhecimento.", optimalDuration: "30-45min por materia, alternando"),
        StudyMethod(id: "practice-testing", name: "Simulados", icon: "FileCheck", description: "Resolver questoes e provas anteriores", howItWorks: "Resolver questoes de bancas reais. Feedback imediato com explicacao detalhada. Melhor preditor de performance.", optimalDuration: "1-2h por sessao de simulado"),
    ]

    struct PomodoroPreset {
        let id: String
        let name: String
        let work: Int
        let shortBreak: Int
        let longBreak: Int
        let rounds: Int
    }

    static let pomodoroPresets: [PomodoroPreset] = [
        PomodoroPreset(id: "classic", name: "Classico", work: 25, shortBreak: 5, longBreak: 15, rounds: 4),
        PomodoroPreset(id: "deep", name: "Estudo Profundo", work: 50, shortBreak: 10, longBreak: 30, rounds: 3),
        PomodoroPreset(id: "sprint", name: "Sprint Rapido", work: 15, shortBreak: 3, longBreak: 10, rounds: 6),
        PomodoroPreset(id: "exam", name: "Simulado", work: 90, shortBreak: 15, longBreak: 30, rounds: 2),
    ]

    struct DailyStudyGoal {
        let id: String
        let label: String
        let hours: Double
        let description: String
    }

    static let dailyStudyGoals: [DailyStudyGoal] = [
        DailyStudyGoal(id: "light", label: "1-2 horas", hours: 1.5, description: "Revisao e manutencao"),
        DailyStudyGoal(id: "moderate", label: "2-4 horas", hours: 3, description: "Estudo regular"),
        DailyStudyGoal(id: "intense", label: "4-6 horas", hours: 5, description: "Preparacao ativa"),
        DailyStudyGoal(id: "marathon", label: "6+ horas", hours: 7, description: "Modo residencia"),
    ]

    // MARK: Plans

    static let trialDays = 7

    struct PlanLimits {
        let coachQuestionsPerDay: Int
        let flashcards: Int
        let simuladosPerWeek: Int
        let pdfUploads: Int
        let googleCalendar: Bool
        let googleDrive: Bool
        let aiStudyPlan: Bool
        let prioritySupport: Bool
    }

    struct Plan {
        let id: String
        let name: String
        let description: String
        let monthlyPrice: Int
        let annualPrice: Int
        let trialDays: Int
        let features: [String]
        let limits: PlanLimits
    }

    static let plans: [Plan] = [
        Plan(id: "free", name: "Free", description: "Para comecar a estudar", monthlyPrice: 0, annualPrice: 0, trialDays: 0, features: ["5 perguntas a Vita por dia", "50 flashcards", "1 simulado por semana", "Agenda basica"], limits: PlanLimits(coachQuestionsPerDay: 5, flashcards: 50, simuladosPerWeek: 1, pdfUploads: 3, googleCalendar: true, googleDrive: true, aiStudyPlan: false, prioritySupport: false)),
        Plan(id: "pro", name: "Pro", description: "Tudo ilimitado para sua aprovacao", monthlyPrice: 2490, annualPrice: 23990, trialDays: 7, features: ["Vita IA ilimitada", "Flashcards e simulados ilimitados", "Upload de PDFs ilimitado", "Agenda inteligente com IA", "Analytics de desempenho"], limits: PlanLimits(coachQuestionsPerDay: -1, flashcards: -1, simuladosPerWeek: -1, pdfUploads: -1, googleCalendar: true, googleDrive: true, aiStudyPlan: false, prioritySupport: false)),
        Plan(id: "premium", name: "Premium", description: "O pacote completo para quem leva a serio", monthlyPrice: 4990, annualPrice: 47990, trialDays: 7, features: ["Tudo do Pro", "Plano de estudo personalizado com IA", "Suporte prioritario"], limits: PlanLimits(coachQuestionsPerDay: -1, flashcards: -1, simuladosPerWeek: -1, pdfUploads: -1, googleCalendar: true, googleDrive: true, aiStudyPlan: true, prioritySupport: true)),
    ]

    // MARK: Helpers

    static func levelForXp(_ xp: Int) -> Int {
        var level = 0
        for i in levelThresholds.indices {
            if xp >= levelThresholds[i] { level = i }
            else { break }
        }
        return level
    }

    static func levelThreshold(_ level: Int) -> Int {
        if level < 0 { return 0 }
        if level >= levelThresholds.count { return levelThresholds.last ?? 0 }
        return levelThresholds[level]
    }

    static func subjectsByYear(_ year: Int) -> [Subject] {
        subjects.filter { $0.year.contains(year) }
    }

    static func subjectsByCycle(_ cycleId: String) -> [Subject] {
        subjects.filter { $0.cycle == cycleId }
    }

    static func planLimits(_ planType: String) -> PlanLimits {
        plans.first { $0.id == planType }?.limits ?? plans.first { $0.id == "free" }!.limits
    }
}
