// Auto-generated by @bymav/design-tokens — DO NOT EDIT
// Brand: vita | Source: tokens.json | Regenerate: node generate.mjs
// Theme: Gold Glassmorphism (updated 2026-03-11)

import SwiftUI

// MARK: - Vita Design Tokens

enum VitaTokens {

    // MARK: Dark Colors
    // Background: #0A0A0F (deep near-black) — from mockup vita-app.html
    // Accent:     #C8A050 gold-400 primary — rgba(200,160,80,1.0)
    enum DarkColors {
        // Backgrounds — near-black, very slightly warm (not cyan-tinted)
        static let bg          = Color(red: 0.039, green: 0.039, blue: 0.059)   // #0A0A0F
        static let bgCard      = Color(red: 0.071, green: 0.063, blue: 0.086)   // #120F16 — warm dark
        static let bgElevated  = Color(red: 0.059, green: 0.051, blue: 0.075)   // #0F0D13
        static let bgHover     = Color(red: 0.094, green: 0.082, blue: 0.114)   // #18151D
        static let bgActive    = Color(red: 0.118, green: 0.102, blue: 0.141)   // #1E1A24
        static let bgSubtle    = Color(red: 0.078, green: 0.063, blue: 0.031)   // gold-tinted subtle bg
        static let borderSurface = Color(red: 0.118, green: 0.110, blue: 0.141) // #1E1C24

        // Text hierarchy — unchanged (white opacities)
        static let text          = Color(red: 1.000, green: 1.000, blue: 1.000).opacity(0.85)
        static let textSecondary = Color(red: 1.000, green: 1.000, blue: 1.000).opacity(0.55)
        static let textMuted     = Color(red: 1.000, green: 1.000, blue: 1.000).opacity(0.25)

        // Data colors — semantic, unchanged
        static let dataBlue  = Color(red: 0.376, green: 0.647, blue: 0.980)
        static let dataGreen = Color(red: 0.290, green: 0.871, blue: 0.502)
        static let dataAmber = Color(red: 0.984, green: 0.749, blue: 0.141)
        static let dataRed   = Color(red: 0.973, green: 0.443, blue: 0.443)

        // Accent: Gold #C8A050 — rgba(200,160,80) from mockup
        static let accent       = Color(red: 0.784, green: 0.627, blue: 0.314)  // #C8A050 gold-400
        static let accentHover  = Color(red: 0.722, green: 0.525, blue: 0.043)  // #B88600 gold-500
        static let accentSubtle = Color(red: 0.784, green: 0.627, blue: 0.314).opacity(0.08)
        static let border       = Color(red: 0.784, green: 0.627, blue: 0.314).opacity(0.08)
        static let borderHover  = Color(red: 0.784, green: 0.627, blue: 0.314).opacity(0.14)
        static let borderActive = Color(red: 0.784, green: 0.627, blue: 0.314).opacity(0.22)
    }

    // MARK: Light Colors
    enum LightColors {
        static let bg          = Color(red: 0.980, green: 0.976, blue: 0.965)
        static let bgCard      = Color(red: 1.000, green: 1.000, blue: 1.000)
        static let bgElevated  = Color(red: 0.961, green: 0.957, blue: 0.945)
        static let bgHover     = Color(red: 0.941, green: 0.933, blue: 0.918)
        static let bgActive    = Color(red: 0.918, green: 0.906, blue: 0.882)
        static let border      = Color(red: 0.898, green: 0.890, blue: 0.871)
        static let borderHover = Color(red: 0.820, green: 0.800, blue: 0.769)
        static let borderActive = Color(red: 0.612, green: 0.580, blue: 0.525)
        static let text          = Color(red: 0.122, green: 0.110, blue: 0.090)
        static let textSecondary = Color(red: 0.420, green: 0.400, blue: 0.365)
        static let textMuted     = Color(red: 0.612, green: 0.590, blue: 0.545)
        static let dataBlue  = Color(red: 0.231, green: 0.510, blue: 0.965)
        static let dataGreen = Color(red: 0.133, green: 0.773, blue: 0.369)
        static let dataAmber = Color(red: 0.961, green: 0.620, blue: 0.043)
        static let dataRed   = Color(red: 0.937, green: 0.267, blue: 0.267)
        static let accent      = Color(red: 0.722, green: 0.525, blue: 0.043)   // gold-500 for light bg
        static let accentHover = Color(red: 0.608, green: 0.416, blue: 0.027)
        static let accentSubtle = Color(red: 0.722, green: 0.525, blue: 0.043).opacity(0.06)
    }

    // MARK: Primitive Colors
    enum PrimitiveColors {
        // Gold scale — primary brand palette
        static let gold200 = Color(red: 0.929, green: 0.843, blue: 0.627)  // #EDCE9F warm highlight
        static let gold300 = Color(red: 0.863, green: 0.737, blue: 0.455)  // #DCBC74
        static let gold400 = Color(red: 0.784, green: 0.627, blue: 0.314)  // #C8A050 primary
        static let gold500 = Color(red: 0.722, green: 0.525, blue: 0.043)  // #B88600 dark gold
        static let gold600 = Color(red: 0.580, green: 0.408, blue: 0.027)  // #946807
        static let goldWarm = Color(red: 0.863, green: 0.671, blue: 0.471) // #DCAB78 warm orange-gold
        static let goldLight = Color(red: 1.000, green: 0.863, blue: 0.627) // #FFDC9F highlight

        // Kept for data viz
        static let blue400  = Color(red: 0.376, green: 0.647, blue: 0.980)
        static let blue500  = Color(red: 0.231, green: 0.510, blue: 0.965)
        static let green400 = Color(red: 0.290, green: 0.871, blue: 0.502)
        static let green500 = Color(red: 0.133, green: 0.773, blue: 0.369)
        static let amber400 = Color(red: 0.984, green: 0.749, blue: 0.141)
        static let amber500 = Color(red: 0.961, green: 0.620, blue: 0.043)
        static let red400   = Color(red: 0.973, green: 0.443, blue: 0.443)
        static let red500   = Color(red: 0.937, green: 0.267, blue: 0.267)
        static let indigo400 = Color(red: 0.655, green: 0.545, blue: 0.980)

        // Glow colors — now gold-tinted
        static let glowB = Color(red: 0.863, green: 0.671, blue: 0.314)    // warm gold glow
        static let glowC = Color(red: 0.784, green: 0.549, blue: 0.235)    // amber-gold glow

        // Neutrals
        static let white = Color(red: 1.000, green: 1.000, blue: 1.000)
        static let black = Color(red: 0.000, green: 0.000, blue: 0.000)

        // Legacy aliases (kept for source compatibility)
        static let cyan300 = gold300
        static let cyan400 = gold400
        static let cyan500 = gold500
        static let cyan600 = gold600
        static let orange400 = Color(red: 0.984, green: 0.573, blue: 0.235)
        static let orange500 = Color(red: 0.976, green: 0.451, blue: 0.086)
        static let orange600 = Color(red: 0.918, green: 0.345, blue: 0.047)
        static let orange700 = Color(red: 0.761, green: 0.255, blue: 0.047)
    }

    // MARK: Spacing
    enum Spacing {
        static let xxs: CGFloat = 2
        static let xs: CGFloat = 4
        static let sm: CGFloat = 8
        static let md: CGFloat = 12
        static let lg: CGFloat = 16
        static let xl: CGFloat = 20
        static let _2xl: CGFloat = 24
        static let _3xl: CGFloat = 32
        static let _4xl: CGFloat = 48
    }

    // MARK: Radius
    enum Radius {
        static let sm: CGFloat = 8
        static let md: CGFloat = 12
        static let lg: CGFloat = 16
        static let xl: CGFloat = 20
        static let full: CGFloat = 9999
    }

    // MARK: Elevation
    enum Elevation {
        static let none: CGFloat = 0
        static let xs: CGFloat = 1
        static let sm: CGFloat = 2
        static let md: CGFloat = 4
        static let lg: CGFloat = 8
        static let xl: CGFloat = 12
        static let _2xl: CGFloat = 24
    }

    // MARK: Typography
    enum Typography {
        static let fontSizeXs: CGFloat = 10
        static let fontSizeSm: CGFloat = 12
        static let fontSizeBase: CGFloat = 13
        static let fontSizeMd: CGFloat = 14
        static let fontSizeLg: CGFloat = 16
        static let fontSizeXl: CGFloat = 20
        static let fontSize_2xl: CGFloat = 24
        static let fontSize_3xl: CGFloat = 30

        static let fontWeightNormal: CGFloat = 400
        static let fontWeightMedium: CGFloat = 500
        static let fontWeightSemibold: CGFloat = 600
        static let fontWeightBold: CGFloat = 700

        static let letterSpacingTight: CGFloat = -0.4
        static let letterSpacingNormal: CGFloat = 0
        static let letterSpacingWide: CGFloat = 0.5

        static let fontFamilySans = "Space Grotesk"
        static let fontFamilyMono = "JetBrains Mono"
        static let fontFamilyIosBody = "SF Pro Text"
        static let fontFamilyIosDisplay = "SF Pro Display"
    }

    // MARK: Animation
    enum Animation {
        static let durationFast: Double = 0.15
        static let durationNormal: Double = 0.30
        static let durationSlow: Double = 0.50
        static let easeOut = "cubic-bezier(0.33, 1, 0.68, 1)"
    }

    // MARK: Components
    enum Components {
        enum RatingButton {
            static let minHeight: CGFloat = 56
            static let radius: CGFloat = 14
            static let fontSize: CGFloat = 12
            static let iconSize: CGFloat = 16
            static let bgAlpha: Double = 0.08
            static let borderAlpha: Double = 0.18
        }
        enum GlassCard {
            static let radius: CGFloat = 12
            static let bgAlpha: Double = 0.03
            static let borderAlpha: Double = 0.06
        }
        enum ChatBubble {
            static let radius: CGFloat = 16
            static let maxWidth = "85%"
        }
        enum Flashcard {
            static let flipDuration: Double = 0.50
            static let perspective: CGFloat = 1200
            static let frontBorderAlpha: Double = 0.12
            static let backBorderAlpha: Double = 0.12
            static let blur: CGFloat = 16
        }
        enum Chip {
            static let paddingV: CGFloat = 8
            static let paddingH: CGFloat = 14
            static let radius: CGFloat = 9999
            static let fontSize: CGFloat = 11
            static let fontWeight: CGFloat = 500
        }
        enum DeckPill {
            static let paddingV: CGFloat = 4
            static let paddingH: CGFloat = 12
            static let radius: CGFloat = 9999
            static let fontSize: CGFloat = 10
            static let fontWeight: CGFloat = 600
            static let letterSpacing: CGFloat = 0.8
        }
    }
}
