// Auto-generated by @bymav/design-tokens — DO NOT EDIT
// Brand: vita | Source: tokens.json | Regenerate: node generate.mjs

import SwiftUI

// MARK: - Vita Design Tokens

enum VitaTokens {

    // MARK: Dark Colors
    enum DarkColors {
        static let bg = Color(red: 0.016, green: 0.031, blue: 0.035)
        static let bgCard = Color(red: 0.051, green: 0.075, blue: 0.094)
        static let bgElevated = Color(red: 0.039, green: 0.063, blue: 0.078)
        static let bgHover = Color(red: 0.063, green: 0.094, blue: 0.125)
        static let bgActive = Color(red: 0.086, green: 0.125, blue: 0.157)
        static let bgSubtle = Color(red: 0.031, green: 0.184, blue: 0.220)
        static let borderSurface = Color(red: 0.102, green: 0.125, blue: 0.157)
        static let text = Color(red: 1.000, green: 1.000, blue: 1.000).opacity(0.85)
        static let textSecondary = Color(red: 1.000, green: 1.000, blue: 1.000).opacity(0.55)
        static let textMuted = Color(red: 1.000, green: 1.000, blue: 1.000).opacity(0.25)
        static let dataBlue = Color(red: 0.376, green: 0.647, blue: 0.980)
        static let dataGreen = Color(red: 0.290, green: 0.871, blue: 0.502)
        static let dataAmber = Color(red: 0.984, green: 0.749, blue: 0.141)
        static let dataRed = Color(red: 0.973, green: 0.443, blue: 0.443)
        static let accent = Color(red: 0.133, green: 0.827, blue: 0.933)
        static let accentHover = Color(red: 0.024, green: 0.714, blue: 0.831)
        static let accentSubtle = Color(red: 0.133, green: 0.827, blue: 0.933).opacity(0.08)
        static let border = Color(red: 0.133, green: 0.827, blue: 0.933).opacity(0.08)
        static let borderHover = Color(red: 0.133, green: 0.827, blue: 0.933).opacity(0.14)
        static let borderActive = Color(red: 0.133, green: 0.827, blue: 0.933).opacity(0.2)
    }

    // MARK: Light Colors
    enum LightColors {
        static let bg = Color(red: 0.980, green: 0.980, blue: 0.980)
        static let bgCard = Color(red: 1.000, green: 1.000, blue: 1.000)
        static let bgElevated = Color(red: 0.961, green: 0.961, blue: 0.961)
        static let bgHover = Color(red: 0.941, green: 0.941, blue: 0.941)
        static let bgActive = Color(red: 0.910, green: 0.910, blue: 0.933)
        static let border = Color(red: 0.898, green: 0.898, blue: 0.898)
        static let borderHover = Color(red: 0.820, green: 0.835, blue: 0.859)
        static let borderActive = Color(red: 0.612, green: 0.639, blue: 0.686)
        static let text = Color(red: 0.122, green: 0.161, blue: 0.216)
        static let textSecondary = Color(red: 0.420, green: 0.447, blue: 0.502)
        static let textMuted = Color(red: 0.612, green: 0.639, blue: 0.686)
        static let dataBlue = Color(red: 0.231, green: 0.510, blue: 0.965)
        static let dataGreen = Color(red: 0.133, green: 0.773, blue: 0.369)
        static let dataAmber = Color(red: 0.961, green: 0.620, blue: 0.043)
        static let dataRed = Color(red: 0.937, green: 0.267, blue: 0.267)
        static let accent = Color(red: 0.024, green: 0.714, blue: 0.831)
        static let accentHover = Color(red: 0.031, green: 0.569, blue: 0.698)
        static let accentSubtle = Color(red: 0.024, green: 0.714, blue: 0.831).opacity(0.06)
    }

    // MARK: Primitive Colors
    enum PrimitiveColors {
        static let cyan300 = Color(red: 0.404, green: 0.910, blue: 0.976)
        static let cyan400 = Color(red: 0.133, green: 0.827, blue: 0.933)
        static let cyan500 = Color(red: 0.024, green: 0.714, blue: 0.831)
        static let cyan600 = Color(red: 0.031, green: 0.569, blue: 0.698)
        static let orange400 = Color(red: 0.984, green: 0.573, blue: 0.235)
        static let orange500 = Color(red: 0.976, green: 0.451, blue: 0.086)
        static let orange600 = Color(red: 0.918, green: 0.345, blue: 0.047)
        static let orange700 = Color(red: 0.761, green: 0.255, blue: 0.047)
        static let blue400 = Color(red: 0.376, green: 0.647, blue: 0.980)
        static let blue500 = Color(red: 0.231, green: 0.510, blue: 0.965)
        static let green400 = Color(red: 0.290, green: 0.871, blue: 0.502)
        static let green500 = Color(red: 0.133, green: 0.773, blue: 0.369)
        static let amber400 = Color(red: 0.984, green: 0.749, blue: 0.141)
        static let amber500 = Color(red: 0.961, green: 0.620, blue: 0.043)
        static let red400 = Color(red: 0.973, green: 0.443, blue: 0.443)
        static let red500 = Color(red: 0.937, green: 0.267, blue: 0.267)
        static let indigo400 = Color(red: 0.655, green: 0.545, blue: 0.980)
        static let glowB = Color(red: 0.000, green: 0.898, blue: 1.000)
        static let glowC = Color(red: 0.251, green: 0.769, blue: 1.000)
        static let white = Color(red: 1.000, green: 1.000, blue: 1.000)
        static let black = Color(red: 0.000, green: 0.000, blue: 0.000)
    }

    // MARK: Spacing
    enum Spacing {
        static let xxs: CGFloat = 2
        static let xs: CGFloat = 4
        static let sm: CGFloat = 8
        static let md: CGFloat = 12
        static let lg: CGFloat = 16
        static let xl: CGFloat = 20
        static let _2xl: CGFloat = 24
        static let _3xl: CGFloat = 32
        static let _4xl: CGFloat = 48
    }

    // MARK: Radius
    enum Radius {
        static let sm: CGFloat = 8
        static let md: CGFloat = 12
        static let lg: CGFloat = 16
        static let xl: CGFloat = 20
        static let full: CGFloat = 9999
    }

    // MARK: Elevation
    enum Elevation {
        static let none: CGFloat = 0
        static let xs: CGFloat = 1
        static let sm: CGFloat = 2
        static let md: CGFloat = 4
        static let lg: CGFloat = 8
        static let xl: CGFloat = 12
        static let _2xl: CGFloat = 24
    }

    // MARK: Typography
    enum Typography {
        static let fontSizeXs: CGFloat = 10
        static let fontSizeSm: CGFloat = 12
        static let fontSizeBase: CGFloat = 13
        static let fontSizeMd: CGFloat = 14
        static let fontSizeLg: CGFloat = 16
        static let fontSizeXl: CGFloat = 20
        static let fontSize_2xl: CGFloat = 24
        static let fontSize_3xl: CGFloat = 30

        static let fontWeightNormal: CGFloat = 400
        static let fontWeightMedium: CGFloat = 500
        static let fontWeightSemibold: CGFloat = 600
        static let fontWeightBold: CGFloat = 700

        static let letterSpacingTight: CGFloat = -0.4
        static let letterSpacingNormal: CGFloat = 0
        static let letterSpacingWide: CGFloat = 0.5

        static let fontFamilySans = "Space Grotesk"
        static let fontFamilyMono = "JetBrains Mono"
        static let fontFamilyIosBody = "SF Pro Text"
        static let fontFamilyIosDisplay = "SF Pro Display"
    }

    // MARK: Animation
    enum Animation {
        static let durationFast: Double = 0.15
        static let durationNormal: Double = 0.30
        static let durationSlow: Double = 0.50
        static let easeOut = "cubic-bezier(0.33, 1, 0.68, 1)"
    }

    // MARK: Components
    enum Components {
        enum RatingButton {
            static let minHeight: CGFloat = 56
            static let radius: CGFloat = 14
            static let fontSize: CGFloat = 12
            static let iconSize: CGFloat = 16
            static let bgAlpha: Double = 0.08
            static let borderAlpha: Double = 0.18
        }
        enum GlassCard {
            static let radius: CGFloat = 12
            static let bgAlpha: Double = 0.03
            static let borderAlpha: Double = 0.06
        }
        enum ChatBubble {
            static let radius: CGFloat = 16
            static let maxWidth = "85%"
        }
        enum Flashcard {
            static let flipDuration: Double = 0.50
            static let perspective: CGFloat = 1200
            static let frontBorderAlpha: Double = 0.12
            static let backBorderAlpha: Double = 0.12
            static let blur: CGFloat = 16
        }
        enum Chip {
            static let paddingV: CGFloat = 8
            static let paddingH: CGFloat = 14
            static let radius: CGFloat = 9999
            static let fontSize: CGFloat = 11
            static let fontWeight: CGFloat = 500
        }
        enum DeckPill {
            static let paddingV: CGFloat = 4
            static let paddingH: CGFloat = 12
            static let radius: CGFloat = 9999
            static let fontSize: CGFloat = 10
            static let fontWeight: CGFloat = 600
            static let letterSpacing: CGFloat = 0.8
        }
    }
}
